# Generated by Django 5.0.1 on 2024-02-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasting", "0009_shownote"),
    ]

    operations = [
        migrations.RenameField(
            model_name="show",
            old_name="category",
            new_name="categories",
        ),
        migrations.AlterField(
            model_name="show",
            name="categories",
            field=models.CharField(
                help_text="iTunes-Podcast-Categories for this show. Comma separated, use slash to separate subcategory.",
                max_length=255,
                verbose_name="categories",
            ),
        ),
    ]
