# Generated by Django 5.0.1 on 2024-02-06 16:25

from django.db import migrations, models




class Migration(migrations.Migration):
    dependencies = [
        ("podcasting", "0011_alter_episode_original_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="show",
            name="owner_email",
            field=models.EmailField(
                blank=True,
                help_text="Email address of the podcast owner (itunes:owner).",
                max_length=254,
                verbose_name="owner email",
            ),
        ),
        migrations.AddField(
            model_name="show",
            name="owner_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the organization, company or Web site owning the podcast. (itunes:owner)",
                max_length=255,
                verbose_name="owner name",
            ),
        ),
    ]
