# Generated by Django 5.0.1 on 2024-02-06 16:29

from django.db import migrations

def noop(apps, schema_editor):
    pass

def set_owner_from_owner(apps, schema_editor):
    Show = apps.get_model("podcasting", "Show")
    db_alias = schema_editor.connection.alias
    for show in Show.objects.using(db_alias).all():
        show.owner_name = f"{show.owner.first_name} {show.owner.last_name}"
        show.owner_email = show.owner.email
        show.save()



class Migration(migrations.Migration):
    dependencies = [
        ("podcasting", "0012_show_owner_email_show_owner_name"),
    ]

    operations = [migrations.RunPython(set_owner_from_owner, noop)]
