# Generated by Django 5.0.1 on 2024-02-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasting", "0015_alter_enclosure_mime"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="transcript",
            field=models.URLField(
                blank=True,
                default="",
                help_text="URL of the transcript file (vtt).",
                verbose_name="Transcript-URL",
            ),
        ),
    ]
