# Generated by Django 5.0.14 on 2026-02-09 00:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasting", "0016_episode_transcript"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enclosure",
            name="mime",
            field=models.CharField(
                choices=[
                    ("aiff", "audio/aiff"),
                    ("mp3", "audio/mpeg"),
                    ("mp4", "audio/mp4"),
                    ("ogg", "audio/ogg"),
                    ("opus", "audio/opus"),
                    ("flac", "audio/flac"),
                    ("wav", "audio/wav"),
                    ("html", "text/html"),
                ],
                help_text="Supports mime types of: aiff, mp3, mp4, ogg, opus, flac, wav, html",
                max_length=4,
                verbose_name="mime format",
            ),
        ),
    ]
